/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// dotprod_demo_fp
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78002/CNN --prefix dotprod_demo_fp --checkpoint-file trained/ai87-dot_emb_112_checkpoint_fp-q.pth.tar --config-file networks/ai87-dotprod.yaml --start-layer 73 --weight-start 2000 --device MAX78002 --timer 0 --display-checkpoint --verbose

// DO NOT EDIT - regenerate this file instead!

// Configuring 74 layers
// Input data: HWC
// Layer 73: 64x1x1, no pooling, linear, no activation, 32x1x1 output

// Final Scales: {73: 0}

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn_1.h"
#include "cnn_5.h"
#include "weights.h"

void CNN_5_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x51000000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x52000000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x53000000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x54000000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

static const uint32_t kernels_5[] = KERNELS_5;

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x51000000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x51000000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

int cnn_load_bias(void)
{
  // Not used in this network
  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x51000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x52000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x53000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x54000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x51000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x52000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x53000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x54000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x5100000c) = 0x00001880; // Clear registers
  *((volatile uint32_t *) 0x5200000c) = 0x00001880; // Clear registers
  *((volatile uint32_t *) 0x5300000c) = 0x00001880; // Clear registers
  *((volatile uint32_t *) 0x5400000c) = 0x00001880; // Clear registers
  while ((*((volatile uint32_t *) 0x5100000c) & 0x2000000) != 0x2000000); // Wait for clear
  while ((*((volatile uint32_t *) 0x5200000c) & 0x2000000) != 0x2000000); // Wait for clear
  while ((*((volatile uint32_t *) 0x5300000c) & 0x2000000) != 0x2000000); // Wait for clear
  while ((*((volatile uint32_t *) 0x5400000c) & 0x2000000) != 0x2000000); // Wait for clear
  *((volatile uint32_t *) 0x5100000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5200000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5300000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5400000c) = 0x00000000; // Reset BIST

  *((volatile uint32_t *) 0x51000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x51000008) = 0x00004949; // Layer count
  *((volatile uint32_t *) 0x52000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x52000008) = 0x00004949; // Layer count
  *((volatile uint32_t *) 0x53000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x53000008) = 0x00004949; // Layer count
  *((volatile uint32_t *) 0x54000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x54000008) = 0x00004949; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 73 quadrant 0
  *((volatile uint32_t *) 0x51104904) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x51104908) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x51104918) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5110491c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x51104920) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x51104924) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x51104930) = 0x0000e920; // Layer control
  *((volatile uint32_t *) 0x51104934) = 0x000f8000; // Layer control 2
  *((volatile uint32_t *) 0x51104938) = 0x00023378; // Mask count
  *((volatile uint32_t *) 0x5110493c) = 0x00023280; // Mask offset
  *((volatile uint32_t *) 0x51104940) = 0x0000001f; // Output channel count
  *((volatile uint32_t *) 0x5110490c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x51104948) = 0xffffffff; // Mask and processor enables

  // Layer 73 quadrant 1
  *((volatile uint32_t *) 0x52104904) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x52104908) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x52104918) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5210491c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x52104920) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x52104924) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x52104930) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x52104934) = 0x000f8000; // Layer control 2
  *((volatile uint32_t *) 0x52104938) = 0x00023378; // Mask count
  *((volatile uint32_t *) 0x5210493c) = 0x00023280; // Mask offset
  *((volatile uint32_t *) 0x52104940) = 0x0000001f; // Output channel count
  *((volatile uint32_t *) 0x5210490c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x52104948) = 0xffffffff; // Mask and processor enables

  // Layer 73 quadrant 2
  *((volatile uint32_t *) 0x53104904) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x53104908) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x53104918) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5310491c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x53104920) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x53104924) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x53104930) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x53104934) = 0x000f8000; // Layer control 2
  *((volatile uint32_t *) 0x53104938) = 0x00023378; // Mask count
  *((volatile uint32_t *) 0x5310493c) = 0x00023280; // Mask offset
  *((volatile uint32_t *) 0x53104940) = 0x0000001f; // Output channel count
  *((volatile uint32_t *) 0x5310490c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x53104948) = 0xffffffff; // Mask and processor enables

  // Layer 73 quadrant 3
  *((volatile uint32_t *) 0x54104904) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x54104908) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x54104918) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5410491c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x54104920) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x54104924) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x54104930) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x54104934) = 0x000f8000; // Layer control 2
  *((volatile uint32_t *) 0x54104938) = 0x00023378; // Mask count
  *((volatile uint32_t *) 0x5410493c) = 0x00023280; // Mask offset
  *((volatile uint32_t *) 0x54104940) = 0x0000001f; // Output channel count
  *((volatile uint32_t *) 0x5410490c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x54104948) = 0xffffffff; // Mask and processor enables


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x51000000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x52000000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x53000000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x54000000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x51000000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf32)
{
  uint16_t *out_buf = (uint16_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *addr;
  int i;

  // Custom unload for this network, layer 73: 8-bit data, shape: (32, 1, 1)
  addr = (volatile uint32_t *) 0x51804000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr +=  0x8000;
    *out_buf++ = (val & 0xff);
    *out_buf++ = ((val >> 8) & 0xff);
    *out_buf++ = ((val >> 16) & 0xff);
    *out_buf++ = ((val >> 24) & 0xff);
  }
  addr = (volatile uint32_t *) 0x52804000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr +=  0x8000;
    *out_buf++ = (val & 0xff);
    *out_buf++ = ((val >> 8) & 0xff);
    *out_buf++ = ((val >> 16) & 0xff);
    *out_buf++ = ((val >> 24) & 0xff);
  }

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_Delay(MSEC(10)); // Wait for load switches
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  if (clock_source == MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL)
    while ((MXC_GCR->ipll_ctrl & MXC_F_GCR_IPLL_CTRL_RDY) != MXC_F_GCR_IPLL_CTRL_RDY) ; // Wait for PLL

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

// int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
// {
//   mxc_gpio_cfg_t gpio_out;
//   gpio_out.port = port;
//   gpio_out.mask = pin;
//   gpio_out.pad = MXC_GPIO_PAD_NONE;
//   gpio_out.func = MXC_GPIO_FUNC_OUT;
//   MXC_GPIO_Config(&gpio_out);
//   MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

//   return CNN_OK;
// }

// int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
// {
//   mxc_gpio_cfg_t gpio_out;
//   gpio_out.port = port;
//   gpio_out.mask = pin;
//   gpio_out.pad = MXC_GPIO_PAD_NONE;
//   gpio_out.func = MXC_GPIO_FUNC_OUT;
//   MXC_GPIO_Config(&gpio_out);
//   MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

//   return CNN_OK;
// }

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

